appname = casdoor
httpport = 8000
runmode = dev
SessionOn = true
copyrequestbody = true

; Database configuration
driverName = sqlite3
dataSourceName = file:casdoor.db?cache=shared&_busy_timeout=10000
dbName = casdoor

; Redis configuration (optional)
; redisEndpoint =

; Static files
staticdir = ./web/build

; HTTPS configuration
; httpport = 443
; EnableHTTPS = true
; HTTPSCertFile = conf/server.crt
; HTTPSKeyFile = conf/server.key

; Token JWT secret
tokenJwtSecret = 

; LDAP configuration
ldapServerPort = 389
